import { DefaultCommentProvider, type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices, type PartialLangiumSharedServices } from 'langium/lsp';
import { createTypirLangiumServices, initializeLangiumTypirServices, type TypirLangiumServices } from 'typir-langium';
import { BiohackingGeneratedModule, BiohackingGeneratedSharedModule } from './generated/module.js';
import { BiohackingValidator, registerValidationChecks } from './biohacking-validator.js';
import { BiohackingScopeProvider } from './biohacking-scope.js';
import { BiohackingCompletionProvider } from './biohacking-completions.js';
import { BiohackingSemanticTokenProvider } from './biohacking-semantic-tokens.js';
import { BiohackingWorkspaceManager } from './biohacking-workspace.js';
import { BiohackingDocumentationProvider } from './biohacking-documentation-provider.js';
import { reflection } from './generated/ast.js';
import { BiohackingTypeSystem, type BiohackingTypirSpecifics } from './typir/biohacking-type-system.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type BiohackingAddedServices = {
    validation: {
        BiohackingValidator: BiohackingValidator
    },
    lsp: {
        CompletionProvider: BiohackingCompletionProvider
    },
    /**
     * The Typir type system. Owns primitive typing, the class hierarchy built
     * from `type ... extends ...`, and scalar assignability; see
     * typir/biohacking-type-system.ts for the split against BiohackingValidator.
     */
    typir: TypirLangiumServices<BiohackingTypirSpecifics>,
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type BiohackingServices = LangiumServices & BiohackingAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
/**
 * A function rather than a constant because the Typir services need the SHARED
 * services to hook into the document lifecycle, and those only exist once
 * createBiohackingServices has built them.
 */
export const createBiohackingModule = (
    shared: LangiumSharedServices,
): Module<BiohackingServices, PartialLangiumServices & BiohackingAddedServices> => ({
    validation: {
        // Takes the services so it can reach the builtin documents when it
        // builds the interaction catalog (builtin/interactions.bio).
        BiohackingValidator: (services) => new BiohackingValidator(services)
    },
    references: {
        ScopeProvider: (services) => new BiohackingScopeProvider(services)
    },
    lsp: {
        CompletionProvider: (services) => new BiohackingCompletionProvider(services),
        // Langium leaves SemanticTokenProvider optional and unbound by default.
        // For a self-describing DSL that is the difference between a file where
        // only eight reserved words are coloured and one where the metamodel is
        // visible; see biohacking-semantic-tokens.ts.
        SemanticTokenProvider: (services) => new BiohackingSemanticTokenProvider(services)
    },
    documentation: {
        CommentProvider: (services) => new DefaultCommentProvider(services),
        // Evidence linking + dynamic dosing live here: @evidence JSDoc tags,
        // inline PMID/DOI linkification, claim-level annotations and per-kg
        // resolution against the workspace user weight.
        DocumentationProvider: (services) => new BiohackingDocumentationProvider(services)
    },
    typir: () => createTypirLangiumServices<BiohackingTypirSpecifics>(
        shared, reflection, new BiohackingTypeSystem(),
    ),
});

/**
 * Shared-service overrides. Shared rather than language-specific because the
 * workspace manager is one per server, not one per language.
 */
export const BiohackingSharedModule: Module<LangiumSharedServices, PartialLangiumSharedServices> = {
    workspace: {
        WorkspaceManager: (services) => new BiohackingWorkspaceManager(services)
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createBiohackingServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Biohacking: BiohackingServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        BiohackingGeneratedSharedModule,
        BiohackingSharedModule
    );
    const Biohacking = inject(
        createDefaultModule({ shared }),
        BiohackingGeneratedModule,
        createBiohackingModule(shared)
    );
    shared.ServiceRegistry.register(Biohacking);
    registerValidationChecks(Biohacking);
    // Registers Typir's own validation checks and wires the type creator into
    // the document build, so types are (re)built as documents change.
    initializeLangiumTypirServices(Biohacking, Biohacking.typir);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, Biohacking };
}
